### ISSUE TITLE
list page add loading animation when new rows are loaded

### ISSUE THREAD

**Issue by BRaimbault** [psi-mis/connectPWA-pm#45]

**Comment by gregrowles** [comment]
the redeemList is loaded from localStorage - a very fast fetch and 'build' transaction (15 list items at a time); it seems somewhat unnecessary to add this sophisticated functionality only because the pause when waiting for new rows to be added lasts less than 500 milliseconds; if we were doing a 'network fetch' - this would give us longer pauses between screen updates; we can leave on 'Backlog' until necessary

**Comment by gregrowles** [comment]
Animated pulsing circle shows when scrolling to bottom list > triggering load of new items

![pulsing_circle_loading.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bfe5d40e87e6b0011ead193/125516c66e82c728ace21e0d46f88196308b8daeb0eab651a751f5ab25492677200aa4693cc7f33ab0487e021b4d44be440b5f42f5f88e23f7bf3c778b5d0bed876c0b26923a19a5aa9e0dfd50e474d412dcfce9c85ecafa3c22ed8a8a4b381b0d1b80fc5b37a59f5985.gif)
